// <auto-generated />
using System;
using BTCPayServer.Plugins.Electrum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Electrum.Migrations
{
    [DbContext(typeof(ElectrumDbContext))]
    [Migration("20260408000000_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("electrum")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .UseIdentityByDefaultColumns();

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.SyncState", b =>
            {
                b.Property<string>("Key")
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Value")
                    .HasColumnType("text");

                b.HasKey("Key");

                b.ToTable("sync_state", "electrum");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedAddress", b =>
            {
                b.Property<string>("Scripthash")
                    .HasColumnType("text");

                b.Property<string>("Address")
                    .HasColumnType("text");

                b.Property<bool>("IsChange")
                    .HasColumnType("boolean");

                b.Property<bool>("IsUsed")
                    .HasColumnType("boolean");

                b.Property<string>("KeyPath")
                    .HasColumnType("text");

                b.Property<byte[]>("ScriptPubKey")
                    .HasColumnType("bytea");

                b.Property<string>("WalletId")
                    .HasColumnType("text");

                b.HasKey("Scripthash");

                b.HasIndex("WalletId");

                b.ToTable("tracked_addresses", "electrum");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedTransaction", b =>
            {
                b.Property<string>("Txid")
                    .HasColumnType("text");

                b.Property<string>("WalletId")
                    .HasColumnType("text");

                b.Property<long>("BalanceChange")
                    .HasColumnType("bigint");

                b.Property<string>("BlockHash")
                    .HasColumnType("text");

                b.Property<long?>("BlockHeight")
                    .HasColumnType("bigint");

                b.Property<long?>("Fee")
                    .HasColumnType("bigint");

                b.Property<byte[]>("RawTx")
                    .HasColumnType("bytea");

                b.Property<DateTimeOffset>("SeenAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Txid", "WalletId");

                b.HasIndex("WalletId");

                b.ToTable("transactions", "electrum");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedUtxo", b =>
            {
                b.Property<string>("Outpoint")
                    .HasColumnType("text");

                b.Property<string>("BlockHash")
                    .HasColumnType("text");

                b.Property<long?>("BlockHeight")
                    .HasColumnType("bigint");

                b.Property<bool>("IsSpent")
                    .HasColumnType("boolean");

                b.Property<string>("KeyPath")
                    .HasColumnType("text");

                b.Property<string>("Scripthash")
                    .HasColumnType("text");

                b.Property<byte[]>("ScriptPubKey")
                    .HasColumnType("bytea");

                b.Property<DateTimeOffset>("SeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("SpendingTxid")
                    .HasColumnType("text");

                b.Property<string>("Txid")
                    .HasColumnType("text");

                b.Property<long>("Value")
                    .HasColumnType("bigint");

                b.Property<int>("Vout")
                    .HasColumnType("integer");

                b.Property<string>("WalletId")
                    .HasColumnType("text");

                b.HasKey("Outpoint");

                b.HasIndex("Scripthash");

                b.HasIndex("WalletId")
                    .HasFilter("NOT \"IsSpent\"");

                b.ToTable("utxos", "electrum");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedWallet", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<int>("ChangeGapIndex")
                    .HasColumnType("integer");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CryptoCode")
                    .HasColumnType("text");

                b.Property<string>("DerivationStrategy")
                    .HasColumnType("text");

                b.Property<int>("ReceiveGapIndex")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("tracked_wallets", "electrum");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedAddress", b =>
            {
                b.HasOne("BTCPayServer.Plugins.Electrum.Data.TrackedWallet", "Wallet")
                    .WithMany()
                    .HasForeignKey("WalletId");

                b.Navigation("Wallet");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedTransaction", b =>
            {
                b.HasOne("BTCPayServer.Plugins.Electrum.Data.TrackedWallet", "Wallet")
                    .WithMany()
                    .HasForeignKey("WalletId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Wallet");
            });

            modelBuilder.Entity("BTCPayServer.Plugins.Electrum.Data.TrackedUtxo", b =>
            {
                b.HasOne("BTCPayServer.Plugins.Electrum.Data.TrackedAddress", "TrackedAddress")
                    .WithMany()
                    .HasForeignKey("Scripthash");

                b.HasOne("BTCPayServer.Plugins.Electrum.Data.TrackedWallet", "Wallet")
                    .WithMany()
                    .HasForeignKey("WalletId");

                b.Navigation("TrackedAddress");

                b.Navigation("Wallet");
            });
#pragma warning restore 612, 618
        }
    }
}
